name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main-ubuntu:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py310", "py311", "py312", "py313", "py314"]'
      os: ubuntu-latest
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.11.1
    with:
      env: '["py310"]'
      os: windows-latest
